### ISSUE TITLE
Modernizing clang-format requirements

### ISSUE THREAD

**Issue by dssgabriel** [kokkos/kokkos-comm#46]
This project may be the right time to depart from KokkosCore's clang-format-**8** requirement and upgrade it to something newer.

I don't know if there are particular (legal?) constraints for such a change, but I suggest we move to _at least_ clang-format-11 (LLVM began supporting `-std=c++20` with clang-11). We could go even newer, e.g. with clang-format-14.

Another (personal) suggestion: we should increase the column limit from 80 to 100 (some might even want 120). With current monitor sizes/resolutions, there's no real reason to keep such a narrow width. Moreover, modern C++ can be quite verbose and the 80-column limit causes lots of unnecessary line breaks.

Updating our clang-format while we still have a relatively small codebase is judicious.

**Comment by dalg24** [comment]
Please go to at least 14.
You might want to survey what popular linux distribution can easily install, like default clang version on the latest LTS of Ubuntu, etc.

**Comment by dssgabriel** [comment]
I'm fine with going as recent as we can. :slightly_smiling_face:   
Ubuntu 24.04 LTS apparently ships LLVM 18! Jammy (22.04) LTS comes with LLVM 14, so we may be fine going with `clang-format-14`.

Are folks against increasing the column limit to 100? 120?

**Comment by dutkalex** [comment]
> Are folks against increasing the column limit to 100? 120?

I would vote for 120: it's a good tradeoff between compactness and readability for C++ I believe

**Comment by cwpearson** [comment]
100 or 120 is fine with me.

I was able to `brew install llvm@14` on my mac and get a `clang-format-14`. I think a PR would need 3 pieces:
* reformatted code
* Switch the CI to use clang-format-14
* make any needed changes to `.clang-format`

**Comment by cwpearson** [comment]
On a linux system I was also able to get clang-format-14 with spack:

```bash
spack install llvm@14 -omp_as_runtime
```

**Comment by cwpearson** [comment]
https://github.com/kokkos/kokkos-comm/pull/52
