### ISSUE TITLE
More idiomatic C++ for CommMode

### ISSUE THREAD

**Issue by cedricchevalier19** [kokkos/kokkos-comm#83]
From https://kokkosteam.slack.com/archives/C06AF7352LE/p1718145132652509?thread_ts=1718128444.322109&cid=C06AF7352LE

> why `send<CommMode>( args...)` instead of `send(CommMode(), args...)`
> I feel the tag type approach as argument is more common nowadays for stuff like ISO C++ library design?

**Comment by dssgabriel** [comment]
As I understand, the idea is to have a syntax similar to how we pass in `KokkosExecSpace`s?
